function trace = parseCSVtraceFile(filename)
    %% Import data from text file
    % Script for importing data from the following text file:
    %
    %    filename:
    %
    % Auto-generated by MATLAB on 16-Nov-2022 23:26:43
    
    %% Set up the Import Options and import the data
    opts = delimitedTextImportOptions("NumVariables", 6);
    
    % Specify range and delimiter
    opts.DataLines = [1, Inf];
    opts.Delimiter = [",", "]"];
    
    % Specify column names and types
    opts.VariableNames = ["x", "y", "w", "h", "trace", "Var6"];
    opts.SelectedVariableNames = ["x", "y", "w", "h", "trace"];
    opts.VariableTypes = ["double", "double", "double", "double", "double", "string"];
    
    % Specify file level properties
    opts.ImportErrorRule = "omitrow";
    opts.MissingRule = "omitrow";
    opts.ExtraColumnsRule = "ignore";
    opts.EmptyLineRule = "read";
    
    % Specify variable properties
    opts = setvaropts(opts, "Var6", "WhitespaceRule", "preserve");
    opts = setvaropts(opts, "Var6", "EmptyFieldRule", "auto");
    opts = setvaropts(opts, ["x", "y", "w", "h", "trace"], "TrimNonNumeric", true);
    opts = setvaropts(opts, ["x", "y", "w", "h", "trace"], "ThousandsSeparator", ",");
    
    % Import the data
    trace = readtable(filename, opts);
    
    
    %% Clear temporary variables
    clear opts

